# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sls-s3-thumbnails # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ] }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } , "/*"] ] }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "S3BucketThumbnails" } , "/*"] ] }
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "S3BucketThumbnails" } ] ] }

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  s3_generate_thumbnails:
    handler: handler.s3_generate_thumbnails
    events:
      - s3:
          bucket: s3-thumbnails-${self:provider.stage}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
          existing: true

#    Define function environment variables here
#    environment:
#      variable2: value2

resources:
  Resources:
    S3BucketThumbnails:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: s3-thumbnails-${self:provider.stage}
  Outputs:
    S3BucketThumbnailsARN:
       Description: "S3 Bucket ARN"
       Value:
          Fn::GetAtt S3BucketThumbnails

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    slim: False
